include:
  - project: accessable-net/gitlab-ci-templates
    file: scheduled_rebase.yml
  - project: accessable-net/gitlab-ci-templates
    file: android-set-version-ci.yml

.only-release: &only-release
  only:
    - master
    - tags

variables:
  UPSTREAM_BRANCH: dev
  VERSION_BUILD_GRADLE_LOCATION: assembly/build.gradle
  VERSION_ANDROID_MANIFEST_LOCATION: assembly/src/main/AndroidManifest.xml
  VERSION_CHANGELOG_DIR_LOCATION: fastlane/metadata/android/en-US/changelogs

  #  For libraries
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

stages:
  - environment
  - build
  - test
  - deploy
  - internal
  - alpha
  - beta
  - production

default:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/cimg/android:2023.12

.build_job:
  stage: build
  tags:
    - saas-linux-large-amd64
  before_script:
    # Fix artifacts permissions
    - sudo chown `whoami`:`groups` $VERSION_BUILD_GRADLE_LOCATION
    - cat $VERSION_BUILD_GRADLE_LOCATION
    - base64 -d $KEYSTORE_FILE > android-signing-keystore.jks
    # Prepare dependencies
    - bundle config set path 'vendor/bundle'
    - bundle install -j $(nproc)
  after_script:
    - rm -f android-signing-keystore.jks || true
  artifacts:
    paths:
      - assembly/build/outputs
  cache:
    paths:
      - .gradle
      - vendor/bundle

buildFdroidDebugApk:
  extends: .build_job
  script:
    - bundle exec fastlane buildFdroidDebugApk

# Generate Apk for direct use
buildFdroidReleaseApk:
  <<: *only-release
  extends: .build_job
  script:
    - bundle exec fastlane buildFdroidReleaseApk

buildGooglePlayReleaseBundle:
  <<: *only-release
  extends: .build_job
  script:
    - bundle exec fastlane buildGooglePlayReleaseBundle

testFdroidDebug:
  allow_failure: true
  stage: test
  dependencies:
    - buildFdroidDebugApk
  before_script:
    # Prepare dependencies
    - bundle config set path 'vendor/bundle'
    - bundle install -j $(nproc)
  script:
    - bundle exec fastlane test
  cache:
    paths:
      - .gradle
      - vendor/bundle
  tags:
    - saas-linux-large-amd64

publishInternal:
  <<: *only-release
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/ruby:alpine
  stage: internal
  dependencies:
    - buildGooglePlayReleaseBundle
  when: manual
  before_script:
    - mv $google_play_service_account_api_key_json ~/.google-play.json
    - apk add build-base
    # Install fastlane etc.
    - bundle config set path 'vendor/bundle'
    - bundle install -j $(nproc)
  after_script:
    - rm ~/.google-play.json
  script:
    - bundle exec fastlane internal
  cache:
    paths:
      - .gradle
      - vendor/bundle
  only:
    - tags

.promote_job:
  <<: *only-release
  image: ruby:alpine
  when: manual
  dependencies:
    - publishInternal
  before_script:
    - mv $google_play_service_account_api_key_json ~/.google-play.json
    - apk add build-base
    - "export VERSION_CODE=$CI_PIPELINE_IID && echo $VERSION_CODE"
    # Install fastlane etc.
    - bundle config set path 'vendor/bundle'
    - bundle install -j $(nproc)
  after_script:
    - rm ~/google-play.json
  cache:
    paths:
      - .gradle
      - vendor/bundle
  only:
    - tags

promoteAlpha:
  extends: .promote_job
  stage: alpha
  script:
    - bundle exec fastlane promote_internal_to_alpha version_code:$VERSION_CODE

promoteBeta:
  extends: .promote_job
  stage: beta
  script:
    - bundle exec fastlane promote_alpha_to_beta version_code:$VERSION_CODE

promoteProduction:
  extends: .promote_job
  stage: production
  # We only allow production promotion on `master` because
  # it has its own production scoped secret variables
  only:
    - $CI_DEFAULT_BRANCH
  script:
    - bundle exec fastlane promote_beta_to_production version_code:$VERSION_CODE
